### ISSUE TITLE
Build context API and get data in other pages

### ISSUE THREAD

**Issue by shiory602** [shiory602/airbnbApp#3]
fetch the data and show an image to display.
Using [Rapid API](https://rapidapi.com/apidojo/api/hotels4/)

**Comment by shiory602** [comment]
# Overview
I tried to fetch data of photos, but I got only URL.
```
        fetch("https://hotels4.p.rapidapi.com/properties/get-hotel-photos?id=1178275040", {
            "method": "GET",
            "headers": {
                "x-rapidapi-key": "725fcffeeamsheb092e027d45b9ep10af3fjsn6de332681721",
                "x-rapidapi-host": "hotels4.p.rapidapi.com"
            }
        })
        .then(response => {
                setPhotos(response);
                console.log(photos);
        })
        .catch(err => {
            console.error(err);
        });
```

# Assumed Procedure
1. Open the top page
2. I can get data in console.

# Problem
1. Open the top page
2. The error shows up

# Environment
- macOS
- High Sierra
- main branch latest version 
`88f45eba65b3696d4d29ab99f73e7feead45a622`

# Errors, etc.
Data displayed in console.log is undefined
The console shows the following:
```
log.js:24 [HMR] Waiting for update signal from WDS...
Top.js:6 []
Top.js:7 undefined
index.js:1 Warning: Invalid DOM property `class`. Did you mean `className`?
    at h5
    at div
    at div
    at div
    at O (http://localhost:3000/static/js/vendors~main.chunk.js:109345:6)
    at TopFooter
    at Top (http://localhost:3000/static/js/main.chunk.js:653:84)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:102596:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:102798:29)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:102231:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:101851:35)
    at HotelProvider (http://localhost:3000/static/js/main.chunk.js:1073:3)
    at App
console.<computed> @ index.js:1
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
validateProperty$1 @ react-dom.development.js:3505
warnUnknownProperties @ react-dom.development.js:3559
validateProperties$2 @ react-dom.development.js:3583
validatePropertiesInDevelopment @ react-dom.development.js:8765
setInitialProperties @ react-dom.development.js:9041
finalizeInitialChildren @ react-dom.development.js:10201
completeWork @ react-dom.development.js:19470
completeUnitOfWork @ react-dom.development.js:22815
performUnitOfWork @ react-dom.development.js:22787
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ index.js:6
./src/index.js @ index.js:8
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ index.js:8
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
webpackHotDevClient.js:138 src/context/HotelContext.js
  Line 32:8:  React Hook useEffect has a missing dependency: 'photos'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
HotelContext.js:24 GET https://hotels4.p.rapidapi.com/properties/get-hotel-photos?id=1178275040 401 (Unauthorized)
(anonymous) @ HotelContext.js:24
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
Top.js:6 https://hotels4.p.rapidapi.com/properties/get-hotel-photos?id=1178275040
Top.js:7 undefined
HotelContext.js:27 {photos: Array(0)}
HotelContext.js:18 {photos: Array(0)}
```

**Comment by shiory602** [comment]
# Solution

I didn't use `json()`. That's why it didn't change to object data.
```
        fetch("https://hotels4.p.rapidapi.com/properties/get-hotel-photos?id=1178275040", {
            "method": "GET",
            "headers": {
                "x-rapidapi-key": "725fcffeeamsheb092e027d45b9ep10af3fjsn6de332681721",
                "x-rapidapi-host": "hotels4.p.rapidapi.com"
            }
        })
        .then(response => {
            response.json().then(data => {
                setPhotos(data);
                console.log(photos);
            })
        })
        .catch(err => {
            console.error(err);
        });
```

**Comment by shiory602** [comment]
#4
